import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-xl p-3">
          <h1>Header tag</h1>
        </header>
        {children}
        <footer className="text-xl p-3">
          <h1>Footer tag</h1>
        </footer>
      </body>
    </html>
  );
}
